services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      network: host
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - db-data:/prod/backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      network: host
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

volumes:
  db-data:
