# fly.toml app configuration file generated for caol-frontend on 2025-09-29T07:15:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'caol-frontend'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile.frontend'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
