CREATE TABLE IF NOT EXISTS cao_cliente (
    co_cliente INTEGER PRIMARY KEY AUTOINCREMENT,
    no_razao TEXT DEFAULT NULL,
    no_fantasia TEXT DEFAULT NULL,
    no_contato TEXT DEFAULT NULL,
    nu_telefone TEXT DEFAULT NULL,
    nu_ramal TEXT DEFAULT NULL,
    nu_cnpj TEXT DEFAULT NULL,
    ds_endereco TEXT DEFAULT NULL,
    nu_numero INTEGER DEFAULT NULL,
    ds_complemento TEXT DEFAULT NULL,
    no_bairro TEXT NOT NULL DEFAULT '',
    nu_cep TEXT DEFAULT NULL,
    no_pais TEXT DEFAULT NULL,
    co_ramo INTEGER DEFAULT NULL,
    co_cidade INTEGER NOT NULL DEFAULT 0,
    co_status INTEGER DEFAULT NULL,
    ds_site TEXT DEFAULT NULL,
    ds_email TEXT DEFAULT NULL,
    ds_cargo_contato TEXT DEFAULT NULL,
    tp_cliente TEXT DEFAULT NULL,
    ds_referencia TEXT DEFAULT NULL,
    co_complemento_status INTEGER DEFAULT NULL,
    nu_fax TEXT DEFAULT NULL,
    ddd2 TEXT DEFAULT NULL,
    telefone2 TEXT DEFAULT NULL
);
