CREATE TABLE IF NOT EXISTS cao_usuario (
    co_usuario TEXT PRIMARY KEY NOT NULL,
    no_usuario TEXT NOT NULL DEFAULT '',
    ds_senha TEXT NOT NULL DEFAULT '',
    co_usuario_autorizacao TEXT DEFAULT NULL,
    nu_matricula INTEGER DEFAULT NULL,
    dt_nascimento DATE DEFAULT NULL,
    dt_admissao_empresa DATE DEFAULT NULL,
    dt_desligamento DATE DEFAULT NULL,
    dt_inclusao DATETIME DEFAULT NULL,
    dt_expiracao DATE DEFAULT NULL,
    nu_cpf TEXT DEFAULT NULL,
    nu_rg TEXT DEFAULT NULL,
    no_orgao_emissor TEXT DEFAULT NULL,
    uf_orgao_emissor TEXT DEFAULT NULL,
    ds_endereco TEXT DEFAULT NULL,
    no_email TEXT DEFAULT NULL,
    no_email_pessoal TEXT DEFAULT NULL,
    nu_telefone TEXT DEFAULT NULL,
    dt_alteracao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    url_foto TEXT DEFAULT NULL,
    instant_messenger TEXT DEFAULT NULL,
    icq INTEGER DEFAULT NULL,
    msn TEXT DEFAULT NULL,
    yms TEXT DEFAULT NULL,
    ds_comp_end TEXT DEFAULT NULL,
    ds_bairro TEXT DEFAULT NULL,
    nu_cep TEXT DEFAULT NULL,
    no_cidade TEXT DEFAULT NULL,
    uf_cidade TEXT DEFAULT NULL,
    dt_expedicao DATE DEFAULT NULL
);
