CREATE TABLE IF NOT EXISTS cao_fatura (
    co_fatura INTEGER PRIMARY KEY AUTOINCREMENT,
    co_cliente INTEGER NOT NULL DEFAULT 0,
    co_sistema INTEGER NOT NULL DEFAULT 0,
    co_os INTEGER NOT NULL DEFAULT 0,
    num_nf INTEGER NOT NULL DEFAULT 0,
    total DECIMAL(15,2) NOT NULL DEFAULT 0,
    valor DECIMAL(15,2) NOT NULL DEFAULT 0,
    data_emissao DATE DEFAULT NULL,
    corpo_nf TEXT NOT NULL,
    comissao_cn DECIMAL(15,2) NOT NULL DEFAULT 0,
    total_imp_inc DECIMAL(15,2) NOT NULL DEFAULT 0
);
