CREATE TABLE IF NOT EXISTS cao_os (
    co_os INTEGER PRIMARY KEY,
    nu_os INTEGER DEFAULT NULL,
    co_sistema INTEGER DEFAULT 0,
    co_usuario TEXT DEFAULT '0',
    co_arquitetura INTEGER DEFAULT 0,
    ds_os TEXT DEFAULT '0',
    ds_caracteristica TEXT DEFAULT '0',
    ds_requisito TEXT DEFAULT NULL,
    dt_inicio DATE DEFAULT NULL,
    dt_fim DATE DEFAULT NULL,
    co_status INTEGER DEFAULT 0,
    diretoria_sol TEXT DEFAULT '0',
    dt_sol DATE DEFAULT NULL,
    nu_tel_sol TEXT DEFAULT '0',
    ddd_tel_sol TEXT DEFAULT NULL,
    nu_tel_sol2 TEXT DEFAULT NULL,
    ddd_tel_sol2 TEXT DEFAULT NULL,
    usuario_sol TEXT DEFAULT '0',
    dt_imp DATE DEFAULT NULL,
    dt_garantia DATE DEFAULT NULL,
    co_email INTEGER DEFAULT NULL,
    co_os_prospect_rel INTEGER DEFAULT NULL
);
